//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_FORM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.DaBans = new HashSet<DaBan>();
            this.Muons = new HashSet<Muon>();
        }
    
        public int MHD { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<int> TongTien { get; set; }
        public int GiamGia { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public bool CThanhVien { get; set; }
    
        public virtual ICollection<DaBan> DaBans { get; set; }
        public virtual ICollection<Muon> Muons { get; set; }
    }
}
