//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_FORM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muon
    {
        public int MaTV { get; set; }
        public int MaSach { get; set; }
        public int MaNVM { get; set; }
        public Nullable<int> SoLuongMuon { get; set; }
        public Nullable<System.DateTime> ThoiGianM { get; set; }
        public Nullable<int> DonGiaMuon { get; set; }
        public int MaHD { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual NV NV { get; set; }
        public virtual Sach Sach { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
