//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_FORM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public NhaCungCap()
        {
            this.CungCaps = new HashSet<CungCap>();
        }
    
        public int MNCC { get; set; }
        public string TenNCC { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> ConHD { get; set; }
        public string Mail { get; set; }
    
        public virtual ICollection<CungCap> CungCaps { get; set; }
    }
}
