//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_FORM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV
    {
        public NV()
        {
            this.CungCaps = new HashSet<CungCap>();
            this.DaBans = new HashSet<DaBan>();
            this.Muons = new HashSet<Muon>();
            this.NV1 = new HashSet<NV>();
        }
    
        public int MNV { get; set; }
        public string HoTenNV { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SoSachBan { get; set; }
        public Nullable<int> luongNV { get; set; }
        public Nullable<int> NgayVang { get; set; }
        public Nullable<System.DateTime> NgayNghiViec { get; set; }
        public Nullable<bool> DaNghi { get; set; }
        public Nullable<int> MNQL { get; set; }
    
        public virtual ICollection<CungCap> CungCaps { get; set; }
        public virtual ICollection<DaBan> DaBans { get; set; }
        public virtual ICollection<Muon> Muons { get; set; }
        public virtual ICollection<NV> NV1 { get; set; }
        public virtual NV NV2 { get; set; }
    }
}
