//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_FORM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DOAN_QUANLYNHASACH_DBMSEntities : DbContext
    {
        public DOAN_QUANLYNHASACH_DBMSEntities()
            : base("name=DOAN_QUANLYNHASACH_DBMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CungCap> CungCaps { get; set; }
        public DbSet<DaBan> DaBans { get; set; }
        public DbSet<HoaDon> HoaDons { get; set; }
        public DbSet<Muon> Muons { get; set; }
        public DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public DbSet<NV> NVs { get; set; }
        public DbSet<Sach> Saches { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<ThanhVien> ThanhViens { get; set; }
        public DbSet<TheLoai> TheLoais { get; set; }
    
        [EdmFunction("DOAN_QUANLYNHASACH_DBMSEntities", "fluongNV")]
        public virtual IQueryable<fluongNV_Result> fluongNV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fluongNV_Result>("[DOAN_QUANLYNHASACH_DBMSEntities].[fluongNV]()");
        }
    
        [EdmFunction("DOAN_QUANLYNHASACH_DBMSEntities", "fThanhVien")]
        public virtual IQueryable<fThanhVien_Result> fThanhVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fThanhVien_Result>("[DOAN_QUANLYNHASACH_DBMSEntities].[fThanhVien]()");
        }
    
        [EdmFunction("DOAN_QUANLYNHASACH_DBMSEntities", "fun_HoaDonOfNhanVien")]
        public virtual IQueryable<fun_HoaDonOfNhanVien_Result> fun_HoaDonOfNhanVien(Nullable<int> maNV)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fun_HoaDonOfNhanVien_Result>("[DOAN_QUANLYNHASACH_DBMSEntities].[fun_HoaDonOfNhanVien](@maNV)", maNVParameter);
        }
    
        [EdmFunction("DOAN_QUANLYNHASACH_DBMSEntities", "fuNhanvienOfQl")]
        public virtual IQueryable<fuNhanvienOfQl_Result> fuNhanvienOfQl(Nullable<int> maNQL)
        {
            var maNQLParameter = maNQL.HasValue ?
                new ObjectParameter("maNQL", maNQL) :
                new ObjectParameter("maNQL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fuNhanvienOfQl_Result>("[DOAN_QUANLYNHASACH_DBMSEntities].[fuNhanvienOfQl](@maNQL)", maNQLParameter);
        }
    
        [EdmFunction("DOAN_QUANLYNHASACH_DBMSEntities", "MuonQuaHan")]
        public virtual IQueryable<MuonQuaHan_Result> MuonQuaHan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<MuonQuaHan_Result>("[DOAN_QUANLYNHASACH_DBMSEntities].[MuonQuaHan]()");
        }
    
        [EdmFunction("DOAN_QUANLYNHASACH_DBMSEntities", "NVinHD")]
        public virtual IQueryable<NVinHD_Result> NVinHD(Nullable<int> maHD)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("maHD", maHD) :
                new ObjectParameter("maHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<NVinHD_Result>("[DOAN_QUANLYNHASACH_DBMSEntities].[NVinHD](@maHD)", maHDParameter);
        }
    
        [EdmFunction("DOAN_QUANLYNHASACH_DBMSEntities", "SearchNhaCC")]
        public virtual IQueryable<SearchNhaCC_Result> SearchNhaCC(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SearchNhaCC_Result>("[DOAN_QUANLYNHASACH_DBMSEntities].[SearchNhaCC](@search)", searchParameter);
        }
    
        public virtual int deleteSach(Nullable<int> maSach)
        {
            var maSachParameter = maSach.HasValue ?
                new ObjectParameter("maSach", maSach) :
                new ObjectParameter("maSach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteSach", maSachParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        [EdmFunction("DOAN_QUANLYNHASACH_DBMSEntities", "fun_SearchCuaNhanVien")]
        public virtual IQueryable<fun_SearchCuaNhanVien_Result> fun_SearchCuaNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fun_SearchCuaNhanVien_Result>("[DOAN_QUANLYNHASACH_DBMSEntities].[fun_SearchCuaNhanVien]()");
        }
    
        public virtual int InsertMuon(Nullable<int> mATV, Nullable<int> mS, Nullable<int> mANV, Nullable<int> soLuong, Nullable<System.DateTime> nMuon, Nullable<System.DateTime> nTra, Nullable<int> mHD, Nullable<System.DateTime> nXuat, Nullable<int> tongTien, Nullable<int> giamGia, Nullable<System.DateTime> nXOA, Nullable<bool> dXOA, Nullable<bool> thanhVien)
        {
            var mATVParameter = mATV.HasValue ?
                new ObjectParameter("MATV", mATV) :
                new ObjectParameter("MATV", typeof(int));
    
            var mSParameter = mS.HasValue ?
                new ObjectParameter("MS", mS) :
                new ObjectParameter("MS", typeof(int));
    
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var nMuonParameter = nMuon.HasValue ?
                new ObjectParameter("NMuon", nMuon) :
                new ObjectParameter("NMuon", typeof(System.DateTime));
    
            var nTraParameter = nTra.HasValue ?
                new ObjectParameter("NTra", nTra) :
                new ObjectParameter("NTra", typeof(System.DateTime));
    
            var mHDParameter = mHD.HasValue ?
                new ObjectParameter("MHD", mHD) :
                new ObjectParameter("MHD", typeof(int));
    
            var nXuatParameter = nXuat.HasValue ?
                new ObjectParameter("NXuat", nXuat) :
                new ObjectParameter("NXuat", typeof(System.DateTime));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(int));
    
            var giamGiaParameter = giamGia.HasValue ?
                new ObjectParameter("GiamGia", giamGia) :
                new ObjectParameter("GiamGia", typeof(int));
    
            var nXOAParameter = nXOA.HasValue ?
                new ObjectParameter("NXOA", nXOA) :
                new ObjectParameter("NXOA", typeof(System.DateTime));
    
            var dXOAParameter = dXOA.HasValue ?
                new ObjectParameter("DXOA", dXOA) :
                new ObjectParameter("DXOA", typeof(bool));
    
            var thanhVienParameter = thanhVien.HasValue ?
                new ObjectParameter("ThanhVien", thanhVien) :
                new ObjectParameter("ThanhVien", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertMuon", mATVParameter, mSParameter, mANVParameter, soLuongParameter, nMuonParameter, nTraParameter, mHDParameter, nXuatParameter, tongTienParameter, giamGiaParameter, nXOAParameter, dXOAParameter, thanhVienParameter);
        }
    
        public virtual ObjectResult<SettingNhanVien_Result> SettingNhanVien(string action, Nullable<int> mNV, string hoTenNV, string sDT, string diaChi, Nullable<int> soSachBan, Nullable<int> luongNV, Nullable<int> ngayVang, Nullable<System.DateTime> ngayNghiViec, Nullable<bool> daNghi, Nullable<int> mNQL, Nullable<bool> status)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var mNVParameter = mNV.HasValue ?
                new ObjectParameter("MNV", mNV) :
                new ObjectParameter("MNV", typeof(int));
    
            var hoTenNVParameter = hoTenNV != null ?
                new ObjectParameter("HoTenNV", hoTenNV) :
                new ObjectParameter("HoTenNV", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soSachBanParameter = soSachBan.HasValue ?
                new ObjectParameter("SoSachBan", soSachBan) :
                new ObjectParameter("SoSachBan", typeof(int));
    
            var luongNVParameter = luongNV.HasValue ?
                new ObjectParameter("luongNV", luongNV) :
                new ObjectParameter("luongNV", typeof(int));
    
            var ngayVangParameter = ngayVang.HasValue ?
                new ObjectParameter("NgayVang", ngayVang) :
                new ObjectParameter("NgayVang", typeof(int));
    
            var ngayNghiViecParameter = ngayNghiViec.HasValue ?
                new ObjectParameter("NgayNghiViec", ngayNghiViec) :
                new ObjectParameter("NgayNghiViec", typeof(System.DateTime));
    
            var daNghiParameter = daNghi.HasValue ?
                new ObjectParameter("DaNghi", daNghi) :
                new ObjectParameter("DaNghi", typeof(bool));
    
            var mNQLParameter = mNQL.HasValue ?
                new ObjectParameter("MNQL", mNQL) :
                new ObjectParameter("MNQL", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SettingNhanVien_Result>("SettingNhanVien", actionParameter, mNVParameter, hoTenNVParameter, sDTParameter, diaChiParameter, soSachBanParameter, luongNVParameter, ngayVangParameter, ngayNghiViecParameter, daNghiParameter, mNQLParameter, statusParameter);
        }
    
        public virtual ObjectResult<SettingThanhVien_Result> SettingThanhVien(string action, Nullable<int> mTV, string hoVaTenTV, string soDT, string diaChi, string mail, Nullable<bool> conSD, Nullable<int> mDThanThiet, Nullable<bool> status)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var mTVParameter = mTV.HasValue ?
                new ObjectParameter("MTV", mTV) :
                new ObjectParameter("MTV", typeof(int));
    
            var hoVaTenTVParameter = hoVaTenTV != null ?
                new ObjectParameter("HoVaTenTV", hoVaTenTV) :
                new ObjectParameter("HoVaTenTV", typeof(string));
    
            var soDTParameter = soDT != null ?
                new ObjectParameter("SoDT", soDT) :
                new ObjectParameter("SoDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var conSDParameter = conSD.HasValue ?
                new ObjectParameter("ConSD", conSD) :
                new ObjectParameter("ConSD", typeof(bool));
    
            var mDThanThietParameter = mDThanThiet.HasValue ?
                new ObjectParameter("MDThanThiet", mDThanThiet) :
                new ObjectParameter("MDThanThiet", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SettingThanhVien_Result>("SettingThanhVien", actionParameter, mTVParameter, hoVaTenTVParameter, soDTParameter, diaChiParameter, mailParameter, conSDParameter, mDThanThietParameter, statusParameter);
        }
    
        [EdmFunction("DOAN_QUANLYNHASACH_DBMSEntities", "fun_SachCon")]
        public virtual IQueryable<fun_SachCon_Result> fun_SachCon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fun_SachCon_Result>("[DOAN_QUANLYNHASACH_DBMSEntities].[fun_SachCon]()");
        }
    
        [EdmFunction("DOAN_QUANLYNHASACH_DBMSEntities", "fun_SearchSach")]
        public virtual IQueryable<fun_SearchSach_Result> fun_SearchSach(string searchSach)
        {
            var searchSachParameter = searchSach != null ?
                new ObjectParameter("searchSach", searchSach) :
                new ObjectParameter("searchSach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fun_SearchSach_Result>("[DOAN_QUANLYNHASACH_DBMSEntities].[fun_SearchSach](@searchSach)", searchSachParameter);
        }
    }
}
