//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_FORM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhVien
    {
        public ThanhVien()
        {
            this.DaBans = new HashSet<DaBan>();
            this.Muons = new HashSet<Muon>();
        }
    
        public int MTV { get; set; }
        public string HoVaTenTV { get; set; }
        public string Diachi { get; set; }
        public string Mail { get; set; }
        public string SoDT { get; set; }
        public Nullable<bool> ConSD { get; set; }
        public Nullable<int> MDThanThiet { get; set; }
    
        public virtual ICollection<DaBan> DaBans { get; set; }
        public virtual ICollection<Muon> Muons { get; set; }
    }
}
